phase: test
distortion: inpaint
wandb_mode: online
run_name: fixed
#jobid: TEST_ # for wandb
log_dir: logs
display_on_inference: 50
# Those are controlled via the bash script now
# K: 0
# H: 0.5
# norm: false
# max_diffusivity: 0.2
inference_steps: 100
diffusivity_schedule: fbb

sde:
  lambda_square: 30
  T: 100
  schedule: cosine # linear, cosine time embedding?
  eps: 0.005

# params for the model architecture UNet imagerec
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

# in train_eval script the model is given by the script:
#pretrain_model_G: "/data/cluster/users/belova/projects/sbalign/aligned_diffusion_bridges/logs/74591-K-0-H-0.5-norm-False-g-0.2/best_model.pt"
#"/data/cluster/users/belova/projects/sbalign/aligned_diffusion_bridges/logs/3igutosp-K-0-H-0.5-norm-False-g-0.2/best_model.pt" 
#/data/cluster/users/belova/projects/sbalign/aligned_diffusion_bridges/logs/74591-K-0-H-0.5-norm-False-g-0.2/best_model.pt # last_model.pt
#"/data/cluster/users/belova/projects/aligned_diffusion_bridges/logs/rmljoco5-K-0-H-0.5-norm-False-g-0.4/last_model.pt"


datasets:
  eval:
    name: Eval_Dataset
    mode: LQGT
    dataroot_GT: celebahq256_imgs/valid/ #train
    dataroot_LQ: celebahq256_imgs/masks/thin
    # we don;t use this transformation in eval, just need it for compatability
    GT_size: ~
    LR_size: ~
    only_get_LQ: false
    only_get_GT: false
    common_shape: 256
  #   use_shuffle: true
  #   n_workers: 1 #4  # per GPU
  #   batch_size: 8
  #   GT_size: 128
  #   LR_size: 128
  #   use_flip: true
  #   use_rot: true
  #   use_swap: false
  #   color: RGB
  # val:
  #   name: Val_Dataset
  #   mode: LQGT
  #   dataroot_GT: Rain100H/val/norain/
  #   dataroot_LQ: Rain100H/val/rain/
  #   GT_size: 128
  #   LR_size: 128