activation: relu
config: null
data_dir: statephate
dataset: statephate
diffusivity_schedule: constant
drift_weight: 1.0
dropout_p: 0.1
early_stop_goal: min
early_stop_metric: val_loss
ema_decay_rate: 0.999
eval_every: 10000
grad_clip_value: 1.0
h_dim: 64
in_dim: 50
inference_every: 0
inference_goal: min
inference_metric: val_rmsd
inference_steps: 100
log_dir: statephate/model
log_every: 1000
lr: 0.001
max_diffusivity: 0.1
n_epochs: 20
n_layers: 4
n_samples: 10000
num_workers: 1
online: false
optim_name: adam
out_dim: 50
reg_weight: 1.0
run_name: tiepgtjon
scheduler: plateau
scheduler_mode: min
split_fracs:
- 0.8
- 0.1
- 0.1
timestep_emb_dim: 32
train_bs: 32
transform: null
use_drift_in_doobs: true
use_grad_noise: false
val_bs: 8
wandb_entity: sb-paired
wandb_id: null
wandb_project: null
weight_decay: 0.001
