activation: silu
config: null
data_dir: statephate
dataset: statephate
diffusivity_schedule: constant
drift_weight: 1.0
dropout_p: 0.1
early_stop_goal: min
early_stop_metric: val_loss
ema_decay_rate: 0.999
eval_every: 10000
grad_clip_value: 10.0
group_name: null
h_dim: 128
in_dim: 50
inference_every: 0
inference_goal: min
inference_metric: val_rmsd
inference_steps: 100
job_type: dev-train
log_dir: ../reproducibility/statephate/model
log_every: 1000
lr: 0.001
max_diffusivity: 1.0
n_epochs: 3
n_layers: 3
n_samples: 10000
num_workers: 1
online: false
optim_name: adamw
out_dim: 50
reg_weight_T: 1.0
reg_weight_t: 1.0
run_name: arpwmwgpi
scheduler: plateau
scheduler_mode: min
scheduler_patience: 10
split_fracs:
- 0.8
- 0.1
- 0.1
task: synthetic
timestep_emb_dim: 128
train_bs: 32
transform: null
use_drift_in_doobs: true
use_grad_noise: false
val_bs: 8
wandb_entity: null
wandb_mode: online
weight_decay: 0.001
