data_dir: diagonal_matching
log_dir: diagonal_matching/model
config: null
wandb_id: null
wandb_entity: sb-paired
wandb_project: null
run_name: hcypfnvih
online: false
dataset: diagonal_matching
n_samples: 10000
train_bs: 32
val_bs: 8
transform: null
split_fracs:
- 0.8
- 0.1
- 0.1
num_workers: 1
in_dim: 2
out_dim: 2
timestep_emb_dim: 32
h_dim: 32
n_layers: 3
activation: selu
dropout_p: 0.1
n_epochs: 20
use_grad_noise: false
drift_weight: 1.0
reg_weight: 1.0
diffusivity_schedule: constant
max_diffusivity: 1.0
use_drift_in_doobs: true
optim_name: adam
lr: 0.001
weight_decay: 0.001
grad_clip_value: 1.0
scheduler: plateau
scheduler_mode: min
ema_decay_rate: 0.999
log_every: 1000
eval_every: 10000
inference_every: 0
inference_steps: 100
inference_metric: val_rmsd
inference_goal: min
early_stop_metric: val_loss
early_stop_goal: min
